### ISSUE TITLE
Week 9 ready for review

### ISSUE THREAD

**Issue by jpdhmc** [jpdhmc/week-9-exercise-jpdhmc#1]
@pawaitemadisoncollege week 9 is complete.

What were your key learning points/takeaways?
Creating RESTful web services.

What challenged you?
I couldn't get the maven dependencies to produce json and xml to work!

What problems did you solve and what resources did you use to solve them?
I ended up outputting the users as plain text.

**Comment by pawaitemadisoncollege** [comment]
Hi @jpdhmc!  This is a good start producing a RESTful service with java code and sets you up well for the next few weeks of work.

- [ ] Producing output in plain text is completely valid, so there's nothing wrong with doing that here. Hopefully you and your team will be able to also produce json in your team project. If you struggle with this, reach out in slack as I'm sure others will be able to help and if not, will learn from the q&a.
- [ ] Review RESTful resource naming standards: https://github.com/jpdhmc/week-9-exercise-jpdhmc/blob/dd85db79183906f8374fe08b363e3404ea4d5bff/src/main/java/edu/matc/rest/GetUser.java#L13 should be @Path("/users")
